# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Navigation' do
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Navigation

  

  platform :ios, '9.0'
  target 'NavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Navigation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Navigation-tvOS

  target 'Navigation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
